# if__name__ == __main__: (this script can be imported OR run standalone)
#                         Function and classes in this module can be reused 
#                         Without the main block of code executing
# Good practice (code is moduler,
#                helps readibility,
#                leaves no global variables,
#                avoid unintended execution)

#               Ex. library = Import library for functionality
#                     When running library directly, display a help page

# [ __(double underscore) is called dunder btw😅 ]


# below comment is generated by Gemini
# ==============================================================================
# THE "GATEKEEPER" LOGIC: if __name__ == '__main__':
# ==============================================================================
# CONCEPT:
# Every Python file has a hidden variable called __name__.
# Python gives this variable a value based on HOW the script is started.
#
# 1. RUN DIRECTLY (e.g., python my_script.py):
#    Python sets __name__ = '__main__'
#    Action: The code inside the 'if' block WILL RUN.
#
# 2. IMPORTED AS A MODULE (e.g., import my_script):
#    Python sets __name__ = 'my_script' (the filename)
#    Action: The code inside the 'if' block WILL NOT RUN.
#
# WHY USE THIS?
# - Modularity: You can use your functions in other projects without 
#   accidentally triggering the logic or inputs of the original script.
# - Safety: Prevents "unintended execution" of code during imports.
# - Cleanliness: Separates "Defining" logic from "Executing" logic.
# ==============================================================================

# both [script1.py] & [script2.py] are used to show the usecase of __name__ == '__main__'

def main():
    pass
    # Your Program goes here

if __name__ == '__main__':
    main()